//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP_Tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int adminID { get; set; }
        public string nume_utilizator { get; set; }
        public string parola { get; set; }
    }
}
